# Generated by Django 2.2.16 on 2022-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220810_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=6, null=True, verbose_name='confirm'),
        ),
    ]
