# Generated by Django 2.2.16 on 2022-08-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
