# Generated by Django 2.2.16 on 2022-08-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220815_0912'),
        ('reviews', '0005_auto_20220815_1039'),
    ]

    operations = [
    ]
